service: essential-mix-api


provider:
  name: aws
  runtime: nodejs6.10
# you can overwrite defaults here
  stage: dev

functions:
  getAllMixes:
    handler: mix.list
    description: Return all the mixes in the index
    events:
      - http:
          path: api
          method: get
    environment:
      algolia_key: ${file(./serverless.env.yml):algolia.key}
      algolia_index: ${file(./serverless.env.yml):algolia.index}

  getSingleMix:
    handler: mix.get
    description: Get mix details by ID
    events:
      - http:
          path: api/{id}
          method: get
    environment:
      algolia_key: ${file(./serverless.env.yml):algolia.key}
      algolia_index: ${file(./serverless.env.yml):algolia.index}

  createNewMix:
    handler: mix.create
    description: Create a new mix in the index
    events:
      - http:
          path: api/
          method: post
    environment:
      algolia_key: ${file(./serverless.env.yml):algolia.key}
      algolia_index: ${file(./serverless.env.yml):algolia.index}


  updateMix:
    handler: mix.update
    description: Update a mix by ID
    events:
      - http:
          path: api/{id}
          method: put
    environment:
      algolia_key: ${file(./serverless.env.yml):algolia.key}
      algolia_index: ${file(./serverless.env.yml):algolia.index}



plugins:
  - serverless-offline
