service: essential-mix-api


provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
  stage: dev

functions:
  mixes:
    handler: handler.mixes

    events:
      - http:
          path: mixes
          method: get


#    Define function environment variables here
    environment:
      algolia_key: ${file(./serverless.env.yml):algolia.key}
      algolia_index: ${file(./serverless.env.yml):algolia.index}

plugins:
  - serverless-offline
